### ISSUE TITLE
Add vfkit to Nixpkgs

### ISSUE THREAD

**Issue by msgilligan** [crc-org/vfkit#130]
It would be nice to be able to install `vfkit` with Nix/Nixpkgs. Especially since projects like Podman are using it.

I opened a packaging request in the Nixpkgs project, see: https://github.com/NixOS/nixpkgs/issues/306179. But I thought it would also be a good idea to open an issue here for completeness and cross-referencing purposes.

**Comment by williamtheaker** [comment]
I think this can be closed as completed by https://github.com/NixOS/nixpkgs/pull/334907

**Comment by cfergeau** [comment]
Thanks!
