### ISSUE TITLE
Switch to Code-Hex/vz/v3

### ISSUE THREAD

**Issue by cfergeau** [crc-org/vfkit#14]
This new version of the bindings wraps the virtualization framework APIs added in macOS 13.
Of interest to us:
- EFI support, which means we should no longer need external kernel/initrd, but directly boot from the disk image as on the other platforms
- virtio-serial support, which qemu-guest-agent uses by default. This would allow us to remove the selinux changes/custom systemd unit from https://github.com/crc-org/snc/pull/595

**Comment by gbraad** [comment]
How will this work for older versions of macOS?

**Comment by cfergeau** [comment]
An error is returned when trying to use the newer APIs on older macOS versions, so this can be dealt with in code.
We could have 2 codepaths while we wait for enough users to migrate to macOS 13, or we could keep using only the old codepaths for a longer while.
Having support for these new features in vfkit would at least allow us to check they are working as expected, and could be useful to other projects even if crc does not make use of them right now.

**Comment by cfergeau** [comment]
This was done in https://github.com/crc-org/vfkit/commit/da9ae56bbaf38514bc50b856f32a2d992e3ca1be
