### ISSUE TITLE
The bundled gin server seems to be running in "debug" mode

### ISSUE THREAD

**Issue by afbjorklund** [crc-org/vfkit#175]
Not sure what happened, but got the debugging output...

```
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
```
```
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://github.com/gin-gonic/gin/blob/master/docs/doc.md#dont-trust-all-proxies for details.
```

----

There is a call to `gin.SetMode(gin.ReleaseMode)`, though?

But no call to `r.SetTrustedProxies(nil)`, as far as I can see.

**Comment by cfergeau** [comment]
Looks like I had a local commit fixing this, but never filed a PR for it :-/

**Comment by cfergeau** [comment]
This was actually already fixed in https://github.com/crc-org/vfkit/commit/20feaee0f3de20c87169a5568e08d0501a0823ce
