### ISSUE TITLE
Wrong size of unit mentioned in the resources

### ISSUE THREAD

**Issue by afbjorklund** [crc-org/vfkit#176]
https://github.com/crc-org/vfkit/blob/main/doc/usage.md#virtual-machine-resources

> The value is in MiB (mibibytes, 1024 * 1024 * 1024 bytes), and the default is 512 MiB.

I think that would make it a GiB ?

And that a MiB is "only" 1024 * 1024

**Comment by cfergeau** [comment]
And MiB is mebibytes, not mibibytes. I've fixed both issues
