### ISSUE TITLE
Use UEFI boot in start-crc-bundle

### ISSUE THREAD

**Issue by cfergeau** [crc-org/vfkit#198]
CRC bundles can now be started using UEFI (https://github.com/crc-org/crc/commit/896d7f45e74778de3c03f302a5f15a0fa3f0453b), the start-crc-bundle could be updated to use `--bootloader efi` instead of `--bootloader linux`

**Comment by lstocchi** [comment]
Forgot to link with the PR. Closed by https://github.com/crc-org/vfkit/pull/201
