### ISSUE TITLE
Ignition support

### ISSUE THREAD

**Issue by cfergeau** [crc-org/vfkit#35]
This is split from https://github.com/crc-org/vfkit/issues/19

With QEMU, ignition gets its config from the firmware configuration (fw_cfg). We cannot use the same mechanism with vfkit as the virtualization framework does not provide the needed APIs.
What is possible instead is to use [the same mechanism as for s390/ppc64](https://github.com/coreos/ignition/commit/3b930b4f2b89c4b2e3bf7a2092bd7d37287297b8) and pass a disk with the ignition id. The raw content of this disk is the ignition config. vfkit only misses a binding for [the BlockDeviceIdentifier property](https://developer.apple.com/documentation/virtualization/vzvirtioblockdeviceconfiguration/3917717-blockdeviceidentifier?language=objc) of virtio-blk devices. I've already added support for this property to my config-vz-split branch.
One limitation with this approach is that it's s390/ppc only, though there were plans to extend it, see
https://github.com/coreos/ignition/pull/999 and https://github.com/coreos/ignition/issues/928.

**Comment by cfergeau** [comment]
With an external kernel/vmlinuz (ie not UEFI boot), I've managed to use `ignition.platform.id=kubevirt` on the kernel command line.
I've used it with a FCOS image, and a separate disk image created as:
```
$ truncate -s 1M ignition-disk
$ mkfs.vfat -n config-2 ignition-disk
$ mount -o loop ./ignition-disk /mnt
$ mkdir -p /mnt/openstack/latest/
$ cp ignition-config.json /mnt/openstack/latest/user_data
```

**Comment by cfergeau** [comment]
We need something which works out of the box though, in particular with uefi boot.

**Comment by cfergeau** [comment]
Current approach will be http communication over vsock

**Comment by BlackHole1** [comment]
Maybe we can close this issues now, as ignition already supports vsock (see: https://github.com/coreos/ignition/pull/1696). And it has been applied in podman as well (https://github.com/containers/podman/blob/main/pkg/machine/applehv/ignition.go).

**Comment by cfergeau** [comment]
I'm considering adding `--ignition $ignition_file_path` flag to vfkit instead of having the support in podman (and similarly, a `--cloud-init` flag), from that perspective this bug would make sense.
But I agree that the initial request is fixed, I'll open new bugs when I get to these.

**Comment by baude** [comment]
> I'm considering adding `--ignition $ignition_file_path` flag to vfkit instead of having the support in podman (and similarly, a `--cloud-init` flag), from that perspective this bug would make sense. But I agree that the initial request is fixed, I'll open new bugs when I get to these.

I think this is generally a good idea; however, one problem for something like podman (anything that uses vfkit), is that podman would be unaware of this entire process.  this makes debugging and awareness more difficult.  if we could consider this in the approach, i'd be willing to help out.
