### ISSUE TITLE
Error: unsupported macOS version

### ISSUE THREAD

**Issue by TheKnarf** [crc-org/vfkit#37]
I tried following the [following instructions](https://github.com/crc-org/vfkit/wiki/vfkit-sanity-check). Downloading the `fedora-coreos-38.20230414.3.0-qemu.x86_64.qcow2` image (then converting it with `qemu-img` and crating an overlay). But I only get the following error:

```
$ ./out/vfkit --cpus 2 --memory 2048 --device virtio-blk,path=overlay.img --device virtio-serial,logFilePath=vfkit.log --device virtio-net,nat,mac=72:20:43:d4:38:62 --device virtio-rng --bootloader efi,variable-store=efi-store,create
INFO[0000] &{2 2048    {[efi variable-store=efi-store create] true}  [virtio-blk,path=overlay.img virtio-serial,logFilePath=vfkit.log virtio-net,nat,mac=72:20:43:d4:38:62 virtio-rng] none:// }
INFO[0000] boot parameters: &{EFIVariableStorePath:efi-store CreateVariableStore:true}
INFO[0000]
INFO[0000] virtual machine parameters:
INFO[0000]      vCPUs: 2
INFO[0000]      memory: 2048 MiB
INFO[0000]
Error: unsupported macOS version
Usage:
  vfkit [flags]

Flags:
  -b, --bootloader strings      bootloader configuration (default [])
  -c, --cpus uint               number of virtual CPUs (default 1)
  -d, --device stringArray      devices
  -h, --help                    help for vfkit
  -i, --initrd string           path to the virtual machine initrd
  -k, --kernel string           path to the virtual machine linux kernel
  -C, --kernel-cmdline string   linux kernel command line
      --log-level string        set log level
  -m, --memory uint             virtual machine RAM size in mibibytes (default 512)
      --restful-uri string      URI address for RestFul services (default "none://")
  -t, --timesync string         sync guest time when host wakes up from sleep
  -v, --version                 version for vfkit

unsupported macOS version
```

My `arch` is:
```
$ arch
i386
```

<img width="698" alt="Screenshot 2023-05-09 at 19 32 50" src="https://github.com/crc-org/vfkit/assets/213777/4dd9a205-877e-415c-98a1-615021ac1605">

**Comment by gbraad** [comment]
I believe the EFI bootloader only works from macOS 13. @cfergeau Am I right?

**Comment by praveenkumar** [comment]
Yes it is only supported or macOS 13 https://developer.apple.com/documentation/virtualization/vzefibootloader?language=objc and https://github.com/crc-org/vfkit/pull/18 where it is added in the codebase.

**Comment by gbraad** [comment]
You would have to specify the parameters yourself, as done in: https://github.com/crc-org/vfkit/blob/main/contrib/scripts/start-crc-bundle.sh or update to macOS 13.

Closing this issue as invalid. Error is as expected.
