### ISSUE TITLE
Add link to fosdem talk

### ISSUE THREAD

**Issue by TheKnarf** [crc-org/vfkit#38]
Maybe add a link to [the FOSDEM 2023 talk](https://fosdem.org/2023/schedule/event/govfkit/) to the readme so that people who want to learn more about vfkit got somewhere to go look?

**Comment by gbraad** [comment]
I would suggest in general more documentation... *wink wink* ;-) @cfergeau, right?

**Comment by cfergeau** [comment]
This can also link to https://containerplumbing.org/sessions/2023/vfkit_a_minimal_  https://www.youtube.com/watch?v=Z2kfaE7H31o https://crc.dev/blog/posts/2023-03-22-containers-plumbing/
