### ISSUE TITLE
GUI does not close with state HardStop

### ISSUE THREAD

**Issue by baude** [crc-org/vfkit#67]
I believe we have a bug (possibly down in vz) where if you run with --gui and the required graphical elements (shown below), when a `HardStop` state change is requested, the GUI is not closed.

Observations:
* the regular `Stop` state change does close the GUI
* With `HardStop`, the machine vm is definitely shutting down

Doing something like:
```
/usr/local/bin/vfkit --bootloader efi,variable-store=/Users/brentbaude/efi-variable-store,create \
	--device virtio-blk,path=/Users/brentbaude/fedora_server.raw \
	--device virtio-net,nat,mac=52:54:00:70:2b:71 \
	--device virtio-rng --device virtio-input,keyboard \
	--device virtio-input,pointing \
	--device virtio-gpu,width=1920,height=1080 \
	--gui \
	--cpus 2 \
	--memory 4192 \
	--restful-uri tcp://localhost:8081
```

And observe the differences in behavior for the following restful calls:

```
brentbaude@Brents-Mac-mini vfkit % curl -X POST  -H 'Content-Type: application/json' -d '{"state": "Stop"}'  http://localhost:8081/vm/state
brentbaude@Brents-Mac-mini vfkit % curl -X POST  -H 'Content-Type: application/json' -d '{"state": "HardStop"}'  http://localhost:8081/vm/state
```

**Comment by cfergeau** [comment]
This is a Code-Hex/vz issue. I've reported it in https://github.com/Code-Hex/vz/issues/150 and https://github.com/cfergeau/vz/tree/hardstop-gui has a fix.

**Comment by cfergeau** [comment]
The update to github.com/Code-Hex/vz 3.5.1 should fix this.
