### ISSUE TITLE
console and keyboard layout

### ISSUE THREAD

**Issue by benoitf** [crc-org/vfkit#92]
when using the vfkit console (started on my case by podman machine start --log-level DEBUG) the keyboard is using english keyboard layout (but keyboard is using for example a french layout)

when using qemu console started by podman machine start as well, it was able to find/use my local keyboard layout

I would expect to have vfkit behaving the same way

vfkit console if I enter `azerty` on a french keyboard, it displays `qwerty`
![image](https://github.com/crc-org/vfkit/assets/436777/58bf6f52-cd19-49da-b5b0-35b4eda74c53)

qemu console, it displays `azerty` as expected
![image](https://github.com/crc-org/vfkit/assets/436777/ead2d597-0175-4bae-aaae-1dbd1a8ae503)

**Comment by cfergeau** [comment]
The vfkit console used by podman is displaying the VM graphical framebuffer, and this behaves as if your keyboard was physically plugged into the VM. This means it honors the keyboard settings configured in the guest, which will be QWERTY by default.

I don't know what the qemu console is, but I'd guess this is using `-display curses`, the keyboard mapping would be done using the host configuration, and thus would be right in your case.

Once https://github.com/crc-org/vfkit/issues/48 is implemented and podman-desktop supports it, this should give you the behaviour you want.
There is not much vfkit can do for the `--gui` keyboard behaviour.
